export { default as Books } from './Books';
export { default as Login } from './Login';
export { default as Loans } from './Loans';
export { default as Overview } from './Overview';
export { default as Register } from './Register';
export { default as Authors } from './Authors';
export { default as ResetPassword } from './ResetPassword';
export { default as Genres } from './Genres';
export { default as Settings } from './Settings';
